font_size 25.0
repaint_delay 0

# https://github.com/kovidgoyal/kitty/issues/884#issuecomment-419117691
scrollback_lines 4294967295

include ~/.cache/wal/colors-kitty.conf

cursor_trail 3
cursor_trail_decay 0.1 0.4

# map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/bin/fzf --no-sort --no-mouse --exact -i
