[Appearance]
color_scheme_path=/usr/share/qt6ct/colors/airy.conf
custom_palette=true
icon_theme=HighContrast
standard_dialogs=gtk3
style=Fusion

[Fonts]
fixed="Roboto Condensed,22,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
general="Sans Serif,22,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=2
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=General, AnimateMenu, AnimateCombo, AnimateTooltip, AnimateToolBox
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=/usr/share/qt6ct/qss/fusion-fixes.qss, /usr/share/qt6ct/qss/scrollbar-simple.qss
toolbutton_style=4
underline_shortcut=2
wheel_scroll_lines=3

[QSSEditor]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\x1T\0\0\x2\x82\0\0\x3\x46\0\0\0\0\0\0\x1T\0\0\x2\x82\0\0\x3\x46\0\0\0\x2\x2\0\0\0\n\0\0\0\0\0\0\0\x1T\0\0\x2\x82\0\0\x3\x46)

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\x1T\0\0\t\xff\0\0\x6\xf3\0\0\0\0\0\0\x1T\0\0\x4\xec\0\0\x3\xef\0\0\0\x2\x2\x4\0\0\n\0\0\0\0\0\0\0\x1T\0\0\t\xff\0\0\x6\xf3)

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
