name: ShellCheck
on: [push, pull_request]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      env:
        SHELLCHECK_OPTS: -e SC2164 -e SC2039 -e SC1091 -e SC1090 -e SC2002
      uses: bewuethr/shellcheck-action@v2

